"""Application configuration.

Loads all environment variables defined in .env.example into module-level
constants. Resolves sample data CSV paths against the project root so tests
work regardless of the current working directory.
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

# backend/config.py -> project root is one level up from this file's parent.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Load .env from the project root if present. ``override=True`` makes the
# file the source of truth even if an earlier process or test left a stale
# value in os.environ (this bit us once with an empty ANTHROPIC_API_KEY).
load_dotenv(PROJECT_ROOT / ".env", override=True)

# --- Anthropic ---
ANTHROPIC_API_KEY: str | None = os.getenv("ANTHROPIC_API_KEY")

# --- Presto / Trino ---
PRESTO_HOST: str | None = os.getenv("PRESTO_HOST")
PRESTO_PORT: int = int(os.getenv("PRESTO_PORT", "8080"))
PRESTO_USER: str | None = os.getenv("PRESTO_USER")
PRESTO_PASSWORD: str | None = os.getenv("PRESTO_PASSWORD")
PRESTO_CATALOG: str = os.getenv("PRESTO_CATALOG", "hive5")
PRESTO_SCHEMA: str = os.getenv("PRESTO_SCHEMA", "development")

# --- Mode flag ---
USE_SAMPLE_DATA: bool = os.getenv("USE_SAMPLE_DATA", "true").lower() == "true"

# --- Payment Intelligence source ---
# "simulated" (default) → read from backend/data/samples/payment_simulation.csv
# "apdp"                → read from APDP Postgres normalized.partner_settlements
# Anything else is treated as "simulated" for safety.
PAYMENT_SOURCE: str = os.getenv("PAYMENT_SOURCE", "simulated").lower()
if PAYMENT_SOURCE not in ("simulated", "apdp"):
    PAYMENT_SOURCE = "simulated"

# --- APDP Postgres (only used when PAYMENT_SOURCE=apdp) ---
APDP_PG_HOST: str = os.getenv("APDP_PG_HOST", "localhost")
APDP_PG_PORT: int = int(os.getenv("APDP_PG_PORT", "5432"))
APDP_PG_DB: str = os.getenv("APDP_PG_DB", "payment_platform")
APDP_PG_USER: str = os.getenv("APDP_PG_USER", "platform_user")
APDP_PG_PASSWORD: str = os.getenv("APDP_PG_PASSWORD", "platform_pass")

# --- FBB audit Postgres (dedicated, separate from APDP) ---
# Holds the zero-commission verification trails. See docker-compose.yml
# (fbb-postgres) and infra/postgres/audit_init.sql. Host port defaults to
# 5544 to avoid clashing with APDP's 5432 / a local Postgres.
FBB_AUDIT_PG_HOST: str = os.getenv("FBB_AUDIT_PG_HOST", "localhost")
FBB_AUDIT_PG_PORT: int = int(os.getenv("FBB_AUDIT_PG_PORT", "5544"))
FBB_AUDIT_PG_DB: str = os.getenv("FBB_AUDIT_PG_DB", "fbb_audit")
FBB_AUDIT_PG_USER: str = os.getenv("FBB_AUDIT_PG_USER", "fbb_audit")
FBB_AUDIT_PG_PASSWORD: str = os.getenv("FBB_AUDIT_PG_PASSWORD", "fbb_audit_pass")

# --- CORS ---
CORS_ORIGINS: list[str] = [
    o.strip()
    for o in os.getenv("CORS_ORIGINS", "http://localhost:5173").split(",")
    if o.strip()
]

# --- Sample data CSVs (absolute paths, used when USE_SAMPLE_DATA=true) ---
#
# Some sources are partitioned by mon_period (one CSV per month) and are
# represented as ``{period: Path}`` dicts. Single-file sources stay as plain
# ``Path`` objects. The data layer (backend/db/queries.py) handles both shapes
# transparently via its ``_load_csv`` helper.
SAMPLE_DATA_PATHS: dict[str, Path | dict[str, Path]] = {
    "fbb_comm_dev_act": {
        "202603": PROJECT_ROOT / "data" / "samples" / "fbb_comm_dev_act_202603.csv",
        "202602": PROJECT_ROOT / "data" / "samples" / "fbb_comm_dev_act_202602.csv",
    },
    "fbb_comm_orsc": {
        "202602": PROJECT_ROOT / "data" / "samples" / "fbb_comm_orsc_sample.csv",
    },
    "usp_dimension": PROJECT_ROOT / "data" / "samples" / "usp_dimension_sample.csv",
    # Phase 3 — Inventory Assurance source: IFS invoice history with implied units.
    "ifs_invoice_history": PROJECT_ROOT / "data" / "samples" / "ifs_invoice_history.csv",
    # Phase 4 — Payment Intelligence: simulated payment dataset generated by
    # backend/data/generate_payment_simulation.py.
    "payment_simulation": PROJECT_ROOT / "data" / "samples" / "payment_simulation.csv",
}
